# Generated by Django 5.1.1 on 2024-09-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana', models.CharField(blank=True, max_length=200, null=True)),
                ('katakana', models.CharField(blank=True, max_length=200, null=True)),
                ('kanji', models.CharField(blank=True, max_length=200, null=True)),
                ('meaning', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('meaning', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='japanese_learner.word')),
            ],
        ),
    ]
