# Generated by Django 5.1.1 on 2024-09-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='points',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='word',
            name='points',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.word')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.story')),
            ],
        ),
        migrations.CreateModel(
            name='InputQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.word')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.story')),
            ],
        ),
    ]
