# Generated by Django 5.1.1 on 2024-09-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0003_alter_word_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='japanese_learner.story'),
        ),
    ]
