# Generated by Django 5.1.1 on 2024-09-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0004_sentence_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
