# Generated by Django 5.1.1 on 2024-09-09 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0005_remove_story_content_story_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='word',
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='japanese_learner.word'),
        ),
    ]
