# Generated by Django 5.1.1 on 2024-09-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0006_remove_multiplechoicequestion_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='story',
        ),
    ]
