# Generated by Django 5.1.1 on 2024-09-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0007_remove_multiplechoicequestion_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='japanese_learner.story'),
        ),
    ]
