# Generated by Django 5.1.1 on 2024-09-09 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0008_word_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='japanese_learner.story'),
        ),
    ]
