# Generated by Django 5.1.1 on 2024-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_learner', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
